### ISSUE TITLE
Is there a direction for human face closing eyes?

### ISSUE THREAD

**Issue by FeiiYin** [betterze/StyleSpace#15]
Is there a direction for human face closing eyes?

**Comment by aRavanel** [comment]
try : (14, 239)

**Comment by alexzeng1206** [comment]
I have tried (14, 239) and find that it can only obtain a squinting rather than a fully closed eye. Any improvement can be made?

**Comment by betterze** [comment]
Actually, I dont hink there will be a channel that fully control eye closing, 'squinting eye' or 'small eye' are the best we can have. This is because the systylegan is trained on FFHQ, and there is not a face with eye closing in the FFHQ dataset. The StyleGAN never see face with eye closing, so it could not generate face with eye closing, and there will not be a channel controling eye closing.

If you want manipulate the 'eye closing' attribute, I suggest you to first finetune the stylegan with faces with 'closing eye', then use the StyleSpace or [StyleCLIP](https://github.com/orpatashnik/StyleCLIP) methods to perform manipulation.
