### ISSUE TITLE
Okay W2S, but S2W?

### ISSUE THREAD

**Issue by manigalati** [betterze/StyleSpace#19]
Hello :)

I have a simple question. I know I can turn a dlatent vector of shape 18x512 into a style vector of 26 entries, and I saw you defined an operation in tensorflow called 'G_synthesis_1/dlatents_in:0' to transform one into the other, which is embedded into the function W2S. I would really like to reverse this operation, having something like S2W, but I cannot find anywhere in the code how to do that. I saw your table in the supplementary material of the paper, I got there is a mapping between W+ and S, but I cannot get it.

Could you help me? Thanks in advance and best regards,

Francesco

**Comment by betterze** [comment]
Dear Francesco,

Thank you for your email. 

In the sup table 2, we show the number of channels in each S layer and its connection to W+. W+ space will translate to S space through a set of affine transformation. Each layer of W+ space contains 512 channels. But for S, the early layer contains 512 channels, later layers contain (32-256) channels. This means for latter layers, it is not possible to precisely invert from S (32) to W+ (512). 

You could try to do latent optimization or train an encoder, similar to image inversion. But the results will not be precise. 

Best Wishes,

Zongze

**Comment by manigalati** [comment]
Oh, I see. I thought that as you use the stylegan2 latent space, it comes that you do S -> W -> original stylegan2 synthesis network. If not like that, what do you feed into the synthesis network? 

Thanks in advance for the availability and best regards,
Francesco

**Comment by betterze** [comment]
The S space is innate in the stylegan architecture, such that W -> S -> img. 

Please refer to sup fig 1 for more detail. And here is the [code](https://github.com/NVlabs/stylegan2/blob/master/training/networks_stylegan2.py#L99) for S space in the original Nvidia stylegan2 implementation. 

The S space is implemented inside the [modulated_conv2d_layer](https://github.com/NVlabs/stylegan2/blob/master/training/networks_stylegan2.py#L89) function. Due to this implementation issue, the s space is not directly accessible as w, w+ or z space. 

In our StyleSpace implementation, we identity the s space through tensor name in [GetSNames](https://github.com/betterze/StyleSpace/blob/ef06425b9bf36b8cd6055534a7d47a5b7d1c5aaa/GetCode.py#L46).
